# Generated by Django 2.2.3 on 2019-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winning_info_fff',
            fields=[
                ('supplier_code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='供应商ID')),
                ('contract_num', models.CharField(max_length=30, verbose_name='合同编号')),
                ('winning_type', models.CharField(max_length=10, verbose_name='中标类型')),
                ('winning_date', models.DateTimeField(auto_now_add=True, verbose_name='中标截止日期')),
                ('supply_end_date', models.DateTimeField(auto_now_add=True, verbose_name='供货截止日期')),
                ('state', models.IntegerField(choices=[(0, '未审核'), (1, '已审核')], default=0)),
            ],
            options={
                'db_table': 'comm.exp_supplier_type_f',
            },
        ),
    ]
